import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: '核心概念',
      items: [
        {
          type: 'autogenerated',
          dirName: 'concepts', // Generate sidebar slice from docs/tutorials/advanced
        },
      ],
    },
    {
      type: 'category',
      label: '基础',
      items: [
        {
          type: 'autogenerated',
          dirName: 'tutorial-basics', // Generate sidebar slice from docs/easy
        },
      ],
    },
    {
      type: 'category',
      label: '进阶',
      items: [
        {
          type: 'autogenerated',
          dirName: 'tutorial-extras', // Generate sidebar slice from docs/advanced
        },
      ],
    },
    // {
    //   type: 'category',
    //   label: '扩展组件',
    //   items: [
    //     {
    //       type: 'autogenerated',
    //       dirName: 'extends-components', // Generate sidebar slice from docs/advanced
    //     },
    //   ],
    // },
    // {
    //   type: 'category',
    //   label: '扩展 UI 库',
    //   items: [
    //     {
    //       type: 'autogenerated',
    //       dirName: 'extends-libs', // Generate sidebar slice from docs/advanced
    //     },
    //   ],
    // },
  ],
  apis: [{ type: 'autogenerated', dirName: 'apis' }],
};

export default sidebars;
